//URLs necessary for program operation
export const URL_Base = "http://localhost:3000";
export const URL_Users = `${URL_Base}/users`;
export const URL_Products = `${URL_Base}/products`;
export const URL_Shopping = `${URL_Base}/shoppings`;
export const URL_WishList = `${URL_Base}/wishlist`;
export const URL_Cart = `${URL_Base}/cart`;
export const URL_Categories = `${URL_Base}/categories`;
export const URL_Sales = `${URL_Base}/sales`;